name: butterflies
description: A Dart application for experimenting with streams, async programming, isolates
# version: 1.0.0
# homepage: https://www.example.com
# author: Miklos Nemeth <nemethmiklos1960@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
